### ISSUE TITLE
Research unit testing frameworks for React

### ISSUE THREAD

**Issue by christophernixon** [christophernixon/DevOps-Pipeline-sweng#4]
Research what options there are for unit-testing React applications. Available options can be added here or as comments on the issue.

**Comment by stauntch** [comment]
YouTube Tutorial on react testing library:
https://www.youtube.com/watch?v=3e1GHCA3GP0
Testing recipes: common testing patterns 
https://reactjs.org/docs/testing-recipes.html


Jest – JavaScript test Runner recommended and supported by Facebook
React Testing Library – library of useful react tests. Recommended and used by facebook
https://github.com/testing-library/react-testing-library


Enzyme – testing utility, used in conjunction with jest.
	Tests outputs and rendering 
Smoke test – Test that components are at least rendering. 
Render tests – Test that components are visually rendered correctly
Unit test – Test individual components/units
Snapshots - https://jestjs.io/docs/en/snapshot-testing
	Renders UI component, takes snapshot and then compares to reference snapshot
