### ISSUE TITLE
Research using webhooks to trigger Travis CI

### ISSUE THREAD

**Issue by christophernixon** [christophernixon/DevOps-Pipeline-sweng#5]
Look at how one would set up github webhooks to link the repository to Travis CI. Solutions could be put here or as comments underneath the issue.

**Comment by crivetimihai** [comment]
You can also use TravisCI as an online alternative to Jenkins.

**Comment by christophernixon** [comment]
Web hooks are not actually needed to trigger Travis CI, instead a .travis.yml file is required at the root of the project. 

Web hooks could be possibly be used to aid Continuous Integration by ensuring that code passes tests before anything is able to merge to master branch, preventing accidental merging of code which doesn't pass build/unit tests.
